// HMK Keeper's Ledger v1 — standalone UI; no changes to the rules kernel.
const STORAGE='hmk-keepers-ledger-v1';
const uuid=()=>globalThis.crypto?.randomUUID?.() ?? `id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const clean=()=>({schemaVersion:1,characters:[],items:[],inventory:[],trash:[],journal:[]});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=()=>new Date().toISOString();
let data=clean(),view='characters',selected=null,editItem=null,query='',category='weapon',notice='';
try{const saved=localStorage.getItem(STORAGE);if(saved)data=validate(JSON.parse(saved));}catch(e){notice='Uložená data nelze načíst. Před další prací doporučujeme exportovat původní úložiště a zkontrolovat chybu.';console.error(e)}
function validate(d){if(!d||d.schemaVersion!==1||!['characters','items','inventory','trash','journal'].every(k=>Array.isArray(d[k])))throw Error('Neplatný formát zálohy');return d}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(data));return true}catch(e){notice='Uložení selhalo (kapacita nebo oprávnění prohlížeče). Ihned exportujte zálohu.';console.error(e);return false}}
function mutate(fn){fn();save();render()}
function button(label,action,cls='secondary'){return `<button class="${cls}" data-action="${action}">${esc(label)}</button>`}
function field(name,label,value='',type='text'){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}"></label>`}
function area(name,label,value=''){return `<label>${esc(label)}<textarea name="${name}">${esc(value)}</textarea></label>`}
function character(id){return data.characters.find(c=>c.id===id)}
function item(id){return data.items.find(i=>i.id===id)}
function main(){let body='';if(view==='characters')body=charactersView();if(view==='sheet')body=sheetView();if(view==='library')body=libraryView();if(view==='trash')body=trashView();if(view==='backup')body=backupView();return `<div class="shell"><header class="mast"><div class="eyebrow">HÂRNMASTER · GAME MASTER CONSOLE</div><h1>The Keeper's Ledger</h1><p>Registr postav · osobní deníky · knihovna vybavení</p></header><div class="layout"><nav class="nav">${[['characters','⚜ Postavy'],['library','⚔ Knihovna'],['trash','♻ Archiv'],['backup','▣ Zálohy']].map(([v,l])=>`<button class="${view===v?'':'secondary'}" data-nav="${v}">${l}</button>`).join('')}</nav><main class="content">${notice?`<div class="notice error">${esc(notice)}</div>`:''}${body}</main></div><footer class="footer">HMK UI v1 · lokální data v tomto prohlížeči · bojové jádro zatím není připojeno</footer></div>`}
function charactersView(){const list=data.characters.filter(c=>(c.name+' '+c.occupation+' '+c.kind).toLowerCase().includes(query.toLowerCase()));return `<div class="topline"><h2>Registr postav (${data.characters.length})</h2>${button('+ Nová postava','new-character')}</div><div class="toolbar"><input id="search" placeholder="Hledat postavu…" value="${esc(query)}"></div>${list.length?`<div class="cards">${list.map(c=>`<article class="card"><span class="pill">${esc(c.kind)}</span><h3>${esc(c.name)}</h3><div class="muted">${esc(c.occupation||'Bez povolání')}</div><div class="muted">${esc(c.description||'')}</div><div class="actions"><button data-open="${esc(c.id)}">Otevřít deník</button><button class="secondary" data-copy="${esc(c.id)}">Kopírovat</button><button class="danger" data-archive="${esc(c.id)}">Archivovat</button></div></article>`).join('')}</div>`:'<div class="empty">Žádné odpovídající postavy.</div>'}`}
function sheetView(){const c=character(selected);if(!c){view='characters';return charactersView()}const inv=data.inventory.filter(x=>x.characterId===c.id);const logs=data.journal.filter(x=>x.characterId===c.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return `<div class="topline"><h2>Osobní deník: ${esc(c.name)}</h2>${button('← Registr','go-characters')}</div><div class="columns"><section class="panel"><h3>Identita</h3><form id="character-form">${field('name','Jméno',c.name)}${field('occupation','Povolání',c.occupation)}<label>Typ<select name="kind"><option ${c.kind==='PC'?'selected':''}>PC</option><option ${c.kind==='NPC'?'selected':''}>NPC</option></select></label>${field('portrait','URL portrétu (nepovinné)',c.portrait)}${area('description','Popis a historie',c.description)}<div class="actions"><button type="submit">Uložit postavu</button></div></form></section><section class="panel"><h3>Vybavení postavy</h3>${inv.length?inv.map(x=>`<div class="list-row"><div><b>${esc(x.snapshot.name)}</b><div class="muted">${esc(x.snapshot.category)} · ${esc(x.condition||'Bez stavu')} · ${esc(x.quantity)} ks</div></div><button class="danger" data-remove-inv="${esc(x.id)}">Odebrat</button></div>`).join(''):'<p class="muted">Zatím bez vybavení.</p>'}<form id="add-inventory"><label>Předmět z knihovny<select name="itemId" required><option value="">Vyberte…</option>${data.items.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} (${esc(i.category)})</option>`).join('')}</select></label>${field('quantity','Počet',1,'number')}${field('condition','Stav / poznámka','')}<button type="submit" ${data.items.length?'':'disabled'}>Přiřadit předmět</button></form><div class="notice tiny">Při přiřazení vzniká samostatná kopie parametrů. Úprava knihovny nezmění již přidělené předměty.</div></section>${hmkSheet(c)}<section class="panel wide"><h3>Osobní zápisník</h3><form id="journal-form">${field('title','Nadpis záznamu')}${area('body','Zápis')}<button type="submit">Přidat záznam</button></form>${logs.map(l=>`<div class="list-row"><div><b>${esc(l.title)}</b><div class="muted">${esc(new Date(l.createdAt).toLocaleString('cs-CZ'))}</div><p>${esc(l.body).replace(/\n/g,'<br>')}</p></div><button class="danger" data-delete-log="${esc(l.id)}">Smazat</button></div>`).join('')}</section></div>`}
function libraryView(){const filtered=data.items.filter(i=>i.category===category&&(i.name+' '+i.description).toLowerCase().includes(query.toLowerCase()));return `<div class="topline"><h2>Knihovna vybavení</h2>${button('+ Nový předmět','new-item')}</div><div class="toolbar"><label>Kategorie<select id="category"><option value="weapon" ${category==='weapon'?'selected':''}>Zbraně</option><option value="shield" ${category==='shield'?'selected':''}>Štíty</option><option value="armor" ${category==='armor'?'selected':''}>Zbroje</option></select></label><input id="search" placeholder="Hledat předmět…" value="${esc(query)}"></div><div class="notice">Základní parametry lze editovat ve strukturovaném formuláři. Bez automatického doplňování neověřených hodnot HMK.</div>${filtered.length?`<div class="cards">${filtered.map(i=>`<article class="card"><h3>${esc(i.name)}</h3><p class="muted">${esc(i.description||'Bez popisu')}</p><p class="tiny">Zdroj: ${esc(i.source||'neuveden')}</p><div class="actions"><button data-edit-item="${esc(i.id)}">Upravit</button><button class="secondary" data-copy-item="${esc(i.id)}">Kopírovat</button><button class="danger" data-delete-item="${esc(i.id)}">Odstranit</button></div></article>`).join('')}</div>`:'<div class="empty">Kategorie zatím neobsahuje předměty.</div>'}`}
function trashView(){return `<h2>Archiv postav</h2><p class="muted">Archivace postavu skryje z registru, ale zachová její deník a vybavení.</p>${data.trash.length?data.trash.map(c=>`<div class="panel list-row"><div><b>${esc(c.name)}</b><div class="muted">${esc(c.occupation)}</div></div><div class="actions"><button data-restore="${esc(c.id)}">Obnovit</button><button class="danger" data-purge="${esc(c.id)}">Definitivně smazat</button></div></div>`).join(''):'<div class="empty">Archiv je prázdný.</div>'}`}
function backupView(){return `<h2>Zálohy a obnova</h2><div class="panel"><p>Data se ukládají lokálně v tomto prohlížeči. Pro přenos mezi zařízeními je nutné exportovat a importovat soubor JSON.</p><div class="actions">${button('Stáhnout JSON zálohu','export')}<label>Importovat JSON zálohu<input type="file" id="import-file" accept=".json,application/json"></label></div><div class="notice error">Import nahradí aktuální lokální data. Před importem si stáhněte zálohu.</div></div>`}
function editor(title,obj,kind){return `<div class="panel"><h2>${esc(title)}</h2><form id="${kind}-editor">${field('name','Název / jméno',obj.name||'')}${kind==='character'?`${field('occupation','Povolání',obj.occupation||'')}<label>Typ<select name="kind"><option>PC</option><option>NPC</option></select></label>${area('description','Popis',obj.description||'')}`:`<label>Kategorie<select name="category">${[['weapon','Zbraň'],['shield','Štít'],['armor','Zbroj']].map(([v,l])=>`<option value="${v}" ${obj.category===v?'selected':''}>${l}</option>`).join('')}</select></label>${area('description','Popis',obj.description||'')}${field('source','Odkaz na zdroj (např. kapitola/strana)',obj.source||'')}${area('properties','Vlastní parametry JSON',JSON.stringify(obj.properties||{},null,2))}`}<div class="actions"><button type="submit">Uložit</button>${button('Zrušit','cancel-editor')}</div></form></div>`}
let overlay=null;
function render(){document.getElementById('app').innerHTML=main()+(overlay||'');}
function ask(msg){return window.confirm(msg)}
document.addEventListener('click',e=>{const t=e.target.closest('[data-action],[data-nav],[data-open],[data-copy],[data-archive],[data-remove-inv],[data-delete-log],[data-edit-item],[data-copy-item],[data-delete-item],[data-restore],[data-purge]');if(!t)return;
if(t.dataset.nav){view=t.dataset.nav;query='';overlay=null;render();return}if(t.dataset.open){selected=t.dataset.open;view='sheet';render();return}
if(t.dataset.copy){const c=character(t.dataset.copy);mutate(()=>data.characters.push({...c,id:uuid(),name:c.name+' (kopie)'}));return}
if(t.dataset.archive){const c=character(t.dataset.archive);if(ask(`Archivovat postavu ${c.name}?`))mutate(()=>{data.characters=data.characters.filter(x=>x.id!==c.id);data.trash.push(c)});return}
if(t.dataset.restore){mutate(()=>{const c=data.trash.find(x=>x.id===t.dataset.restore);data.trash=data.trash.filter(x=>x.id!==c.id);data.characters.push(c)});return}
if(t.dataset.purge){if(ask('DEFINITIVNĚ odstranit postavu, její deník a inventář? Tuto akci nelze vrátit.'))mutate(()=>{const id=t.dataset.purge;data.trash=data.trash.filter(x=>x.id!==id);data.inventory=data.inventory.filter(x=>x.characterId!==id);data.journal=data.journal.filter(x=>x.characterId!==id)});return}
if(t.dataset.removeInv){if(ask('Odebrat předmět z inventáře?'))mutate(()=>data.inventory=data.inventory.filter(x=>x.id!==t.dataset.removeInv));return}
if(t.dataset.deleteLog){if(ask('Smazat zápis?'))mutate(()=>data.journal=data.journal.filter(x=>x.id!==t.dataset.deleteLog));return}
if(t.dataset.editItem){editItem=t.dataset.editItem;const i=item(editItem);overlay=equipmentEditor('Upravit předmět',i);render();return}
if(t.dataset.copyItem){const i=item(t.dataset.copyItem);mutate(()=>data.items.push({...structuredClone(i),id:uuid(),name:i.name+' (kopie)'}));return}
if(t.dataset.deleteItem){if(ask('Odstranit předmět z knihovny? Existující inventáře zůstanou beze změny.'))mutate(()=>data.items=data.items.filter(x=>x.id!==t.dataset.deleteItem));return}
const a=t.dataset.action;if(a==='new-character'){overlay=editor('Nová postava',{},'character');render()}if(a==='new-item'){editItem=null;overlay=equipmentEditor('Nový předmět',{category});render()}if(a==='cancel-editor'){overlay=null;render()}if(a==='go-characters'){view='characters';render()}if(a==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`hmk-ledger-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
});
document.addEventListener('submit',e=>{const f=e.target;if(!['character-editor','item-editor','character-form','add-inventory','journal-form'].includes(f.id))return;e.preventDefault();const v=Object.fromEntries(new FormData(f));if(f.id==='character-editor'){if(!v.name.trim())return alert('Zadejte jméno');mutate(()=>data.characters.push({id:uuid(),name:v.name.trim(),occupation:v.occupation||'',kind:v.kind,description:v.description||'',portrait:''}));overlay=null;return}if(f.id==='character-form'){if(!v.name.trim())return alert('Zadejte jméno');mutate(()=>Object.assign(character(selected),{name:v.name.trim(),occupation:v.occupation,kind:v.kind,description:v.description,portrait:v.portrait}));return}if(f.id==='item-editor'){if(!v.name.trim())return alert('Zadejte název');let properties;try{properties=JSON.parse(v.properties||'{}');if(!properties||Array.isArray(properties)||typeof properties!=='object')throw Error()}catch{return alert('Parametry musí být platný JSON objekt')}mutate(()=>{const record={id:editItem||uuid(),name:v.name.trim(),category:v.category,description:v.description||'',source:v.source||'',properties};if(editItem)Object.assign(item(editItem),record);else data.items.push(record)});overlay=null;return}if(f.id==='add-inventory'){const i=item(v.itemId);const quantity=Number(v.quantity);if(!i||!Number.isSafeInteger(quantity)||quantity<1||quantity>999999)return alert('Vyberte předmět a platný počet');mutate(()=>data.inventory.push({id:uuid(),characterId:selected,sourceItemId:i.id,snapshot:structuredClone(i),quantity,condition:v.condition||''}));return}if(f.id==='journal-form'){if(!v.title.trim()&&!v.body.trim())return;mutate(()=>data.journal.push({id:uuid(),characterId:selected,title:v.title.trim()||'Bez názvu',body:v.body,createdAt:stamp()}))}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;const pos=e.target.selectionStart;render();const input=document.getElementById('search');input.focus();input.setSelectionRange(pos,pos)}});
document.addEventListener('change',async e=>{if(e.target.id==='category'){category=e.target.value;render()}if(e.target.id==='import-file'){const f=e.target.files?.[0];if(!f)return;try{const imported=validate(JSON.parse(await f.text()));if(!ask('Import nahradí všechna současná data. Pokračovat?'))return;data=imported;selected=null;view='characters';notice='Import byl dokončen.';save();render()}catch(err){alert('Neplatný soubor zálohy: '+err.message)}}});
render();


// HMK UI v2: source-grounded character attributes and editable equipment records.
// Rules PDF: Character sheet (Birth/Family/Persona/Standing/Attributes/Skills), pp. 38, 45.
const HMK_ATTRIBUTES={PHYSICAL:[['str','Strength'],['end','Endurance'],['dex','Dexterity'],['agl','Agility'],['per','Perception'],['cml','Comeliness']],MENTAL:[['aur','Aura'],['wil','Will'],['rea','Reasoning'],['cre','Creativity'],['emp','Empathy'],['elo','Eloquence']]};
const HMK_IDENTITY=[['folk','Folk'],['ageGroup','Age group'],['birthdate','Birthdate'],['sunsign','Sunsign'],['birthplace','Birthplace'],['society','Society'],['socialClass','Social class'],['familyOccupation','Parent occupation'],['background','Background'],['estrangement','Estrangement'],['morality','Morality'],['psyche','Psyche'],['home','Home'],['standing','Standing'],['complexion','Complexion'],['hair','Hair'],['eyes','Eyes'],['height','Height'],['weight','Weight'],['handedness','Handedness']];
function numericField(key,label,val){return `<label>${esc(label)}<input type="number" step="1" min="0" max="999" name="${esc(key)}" value="${esc(val??'')}"></label>`}
function hmkSheet(c){const h=c.hmk||{};const a=h.attributes||{};const skills=h.skills||[];return `<section class="panel wide"><h3>HMK · Charakteristika a původ</h3><p class="muted">Struktura podle listu postavy HMK. Prázdné hodnoty znamenají nezadané; aplikace nic nehází ani nedopočítává.</p><form id="hmk-profile-form"><div class="field-grid">${HMK_IDENTITY.map(([k,l])=>field('bio_'+k,l,h[k]??'')).join('')}</div><h3>Physical Attributes</h3><div class="field-grid">${HMK_ATTRIBUTES.PHYSICAL.map(([k,l])=>numericField('attr_'+k,l,a[k])).join('')}</div><h3>Mental Attributes</h3><div class="field-grid">${HMK_ATTRIBUTES.MENTAL.map(([k,l])=>numericField('attr_'+k,l,a[k])).join('')}</div><div class="actions"><button type="submit">Uložit HMK profil</button></div></form></section><section class="panel wide"><h3>Dovednosti · Skills</h3><p class="muted">SB/ML se zadávají ručně podle HMK; automatický výpočet bude připojen až k ověřenému pravidlovému resolveru.</p><div class="table-scroll"><table><thead><tr><th>Skupina</th><th>Dovednost</th><th>SB</th><th>ML</th><th></th></tr></thead><tbody>${skills.map(x=>`<tr><td>${esc(x.group)}</td><td>${esc(x.name)}</td><td>${esc(x.sb??'')}</td><td>${esc(x.ml??'')}</td><td><button class="danger" data-remove-skill="${esc(x.id)}">×</button></td></tr>`).join('')}</tbody></table></div><form id="hmk-skill-form"><div class="field-grid"><label>Skupina<select name="group"><option>Social</option><option>Lore</option><option>Physical</option><option>Esoterica</option><option>Combat</option><option>Craft</option><option>Other</option></select></label>${field('name','Název dovednosti')}${numericField('sb','SB','')}${numericField('ml','ML','')}</div><button type="submit">Přidat dovednost</button></form></section><section class="panel wide"><h3>Zranění a stav postavy</h3><p class="muted">Záznamy jsou evidenční, nikoli výpočet šoku, krvácení nebo léčby. Ty musí zůstat pod kontrolou HMK jádra.</p>${(h.injuries||[]).map(x=>`<div class="list-row"><div><b>${esc(x.location)}</b> · ${esc(x.description)} <span class="muted">${esc(x.severity)}</span></div><button class="danger" data-remove-injury="${esc(x.id)}">Odstranit</button></div>`).join('')}<form id="hmk-injury-form"><div class="field-grid">${field('location','Lokalita zásahu')}${field('severity','Závažnost / označení')}${field('description','Popis poranění')}</div><button type="submit">Zapsat zranění</button></form></section>`}
function equipmentEditor(title,obj){const prop=obj.properties||{};const cat=obj.category||category;const specs=cat==='weapon'?[['attack','Útočné parametry (text)'],['defense','Obranné parametry (text)'],['impact','Impact / damage (text)'],['quality','Weapon Quality (WQ)'],['traits','Traits / vlastnosti']]:cat==='shield'?[['defense','Obranné parametry (text)'],['quality','Shield Quality (WQ)'],['coverage','Krytí / použití'],['traits','Vlastnosti']]:[['material','Materiál'],['coverage','Pokryté lokace'],['layers','Vrstvy / články'],['protection','Ochranné hodnoty dle typu zásahu'],['quality','Kvalita / stav']];return `<div class="panel"><h2>${esc(title)}</h2><form id="hmk-item-form">${field('name','Název',obj.name||'')}<label>Kategorie<select name="category">${[['weapon','Zbraň'],['shield','Štít'],['armor','Zbroj']].map(([v,l])=>`<option value="${v}" ${cat===v?'selected':''}>${l}</option>`).join('')}</select></label>${area('description','Popis',obj.description||'')}${field('source','Pravidlový zdroj (strana/tabulka)',obj.source||'')}<div class="field-grid">${specs.map(([k,l])=>field('spec_'+k,l,prop[k]??'')).join('')}</div><p class="muted">Změna kategorie při editaci nepřepočítává pole; pro jiný typ založte nový záznam. Parametry jsou textové, aby se neinterpretovaly neověřené hodnoty.</p><div class="actions"><button type="submit">Uložit předmět</button><button type="button" class="secondary" data-action="cancel-editor">Zrušit</button></div></form></div>`}
// Capture phase handles new forms before the legacy form dispatcher.
document.addEventListener('submit',e=>{const f=e.target;if(!['hmk-profile-form','hmk-skill-form','hmk-injury-form','hmk-item-form'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();const v=Object.fromEntries(new FormData(f));if(f.id==='hmk-item-form'){if(!String(v.name||'').trim())return alert('Zadejte název');const current=editItem?item(editItem):null;const props={...(current?.properties||{})};for(const [k,val] of Object.entries(v))if(k.startsWith('spec_'))props[k.slice(5)]=val;const record={id:editItem||uuid(),name:v.name.trim(),category:v.category,description:v.description||'',source:v.source||'',properties:props};mutate(()=>{if(current)Object.assign(current,record);else data.items.push(record)});overlay=null;render();return}const c=character(selected);if(!c)return;const h=c.hmk||{};if(f.id==='hmk-profile-form'){const a={...(h.attributes||{})};for(const [k,val] of Object.entries(v)){if(k.startsWith('bio_'))h[k.slice(4)]=val;if(k.startsWith('attr_')){if(val==='')delete a[k.slice(5)];else{const n=Number(val);if(!Number.isSafeInteger(n)||n<0||n>999)return alert('Neplatná charakteristika');a[k.slice(5)]=n}}}h.attributes=a;mutate(()=>{c.hmk=h});return}if(f.id==='hmk-skill-form'){if(!String(v.name||'').trim())return alert('Zadejte název dovednosti');const skill={id:uuid(),group:v.group,name:v.name.trim(),sb:v.sb===''?null:Number(v.sb),ml:v.ml===''?null:Number(v.ml)};if([skill.sb,skill.ml].some(n=>n!==null&&(!Number.isSafeInteger(n)||n<0||n>999)))return alert('Neplatné SB/ML');h.skills=[...(h.skills||[]),skill];mutate(()=>{c.hmk=h});return}if(f.id==='hmk-injury-form'){if(!String(v.location||'').trim())return alert('Zadejte lokalitu');h.injuries=[...(h.injuries||[]),{id:uuid(),location:v.location,description:v.description||'',severity:v.severity||''}];mutate(()=>{c.hmk=h})}},true);
document.addEventListener('click',e=>{const t=e.target.closest('[data-remove-skill],[data-remove-injury]');if(!t)return;const c=character(selected);if(!c||!window.confirm('Odstranit tento záznam?'))return;const key=t.dataset.removeSkill?'skills':'injuries';const id=t.dataset.removeSkill||t.dataset.removeInjury;mutate(()=>{c.hmk=c.hmk||{};c.hmk[key]=(c.hmk[key]||[]).filter(x=>x.id!==id)})});
